export const currentUser = {
  id: "user_1",
  name: "Demo Developer",
  email: "demo@devstash.io",
  image: null,
  isPro: true,
  createdAt: new Date("2024-01-15"),
};

export const itemTypes = [
  {
    id: "type_1",
    name: "Snippet",
    slug: "snippet",
    icon: "Code",
    color: "#3b82f6",
    isSystem: true,
    userId: null,
  },
  {
    id: "type_2",
    name: "Prompt",
    slug: "prompt",
    icon: "Sparkles",
    color: "#8b5cf6",
    isSystem: true,
    userId: null,
  },
  {
    id: "type_3",
    name: "Command",
    slug: "command",
    icon: "Terminal",
    color: "#f97316",
    isSystem: true,
    userId: null,
  },
  {
    id: "type_4",
    name: "Note",
    slug: "note",
    icon: "StickyNote",
    color: "#fde047",
    isSystem: true,
    userId: null,
  },
  {
    id: "type_5",
    name: "Link",
    slug: "link",
    icon: "Link",
    color: "#10b981",
    isSystem: true,
    userId: null,
  },
  {
    id: "type_6",
    name: "File",
    slug: "file",
    icon: "File",
    color: "#6b7280",
    isSystem: true,
    userId: null,
  },
];

export const items = [
  {
    id: "item_1",
    title: "React Custom Hook - useFetch",
    description: "Custom hook for handling API calls with loading and error states",
    content: `export function useFetch(url: string) {\n  const [data, setData] = useState(null);\n  const [loading, setLoading] = useState(true);\n  const [error, setError] = useState(null);\n\n  useEffect(() => {\n    fetch(url)\n      .then(res => res.json())\n      .then(setData)\n      .catch(setError)\n      .finally(() => setLoading(false));\n  }, [url]);\n\n  return { data, loading, error };\n}`,
    contentType: "text",
    language: "typescript",
    isFavorite: false,
    isPinned: true,
    typeId: "type_1",
    userId: "user_1",
    createdAt: new Date("2024-03-01T10:00:00"),
    updatedAt: new Date("2024-03-01T10:00:00"),
  },
  {
    id: "item_2",
    title: "Code Review Assistant",
    description: "AI prompt for reviewing code quality, security, and best practices",
    content: "You are an expert code reviewer. Analyze the following code for:\n1. Security vulnerabilities\n2. Performance issues\n3. Code quality and best practices\n4. Potential bugs\n5. Suggestions for improvement",
    contentType: "text",
    language: null,
    isFavorite: false,
    isPinned: true,
    typeId: "type_2",
    userId: "user_1",
    createdAt: new Date("2024-03-01T07:00:00"),
    updatedAt: new Date("2024-03-01T07:00:00"),
  },
  {
    id: "item_3",
    title: "Docker Cleanup",
    description: "Remove all unused containers, images, and volumes",
    content: "docker system prune -a --volumes",
    contentType: "text",
    language: "bash",
    isFavorite: false,
    isPinned: true,
    typeId: "type_3",
    userId: "user_1",
    createdAt: new Date("2024-02-28T12:00:00"),
    updatedAt: new Date("2024-02-28T12:00:00"),
  },
  {
    id: "item_4",
    title: "API Authentication Flow",
    description: "Notes on implementing JWT authentication with refresh tokens",
    content: "## JWT Auth Flow\n\n1. User logs in with credentials\n2. Server returns access token (15min) + refresh token (7 days)\n3. Access token stored in memory\n4. Refresh token stored in httpOnly cookie\n5. On access token expiry, use refresh token to get new pair",
    contentType: "text",
    language: null,
    isFavorite: false,
    isPinned: false,
    typeId: "type_4",
    userId: "user_1",
    createdAt: new Date("2024-02-27T15:00:00"),
    updatedAt: new Date("2024-02-27T15:00:00"),
  },
  {
    id: "item_5",
    title: "Next.js 15 Documentation",
    description: "Official documentation for Next.js 15 with App Router",
    contentType: "url",
    url: "https://nextjs.org/docs",
    language: null,
    isFavorite: false,
    isPinned: false,
    typeId: "type_5",
    userId: "user_1",
    createdAt: new Date("2024-02-26T09:00:00"),
    updatedAt: new Date("2024-02-26T09:00:00"),
  },
  {
    id: "item_6",
    title: "API Specification.pdf",
    description: "Complete API documentation and endpoint specifications",
    contentType: "file",
    fileName: "api-specification.pdf",
    fileSize: 2516582, // 2.4 MB
    language: null,
    isFavorite: false,
    isPinned: false,
    typeId: "type_6",
    userId: "user_1",
    createdAt: new Date("2024-02-22T14:00:00"),
    updatedAt: new Date("2024-02-22T14:00:00"),
  },
];

export const collections = [
  {
    id: "collection_1",
    name: "React Components",
    description: "Reusable React components and hooks",
    isFavorite: true,
    userId: "user_1",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "collection_2",
    name: "AI Prompts",
    description: "Useful prompts for AI assistants",
    isFavorite: true,
    userId: "user_1",
    createdAt: new Date("2024-01-22"),
    updatedAt: new Date("2024-01-22"),
  },
  {
    id: "collection_3",
    name: "DevOps Scripts",
    description: "Docker, Kubernetes, and deployment scripts",
    isFavorite: false,
    userId: "user_1",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "collection_4",
    name: "Resources",
    description: "Links and documentation",
    isFavorite: false,
    userId: "user_1",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
];

// Stats shown in header
export const stats = {
  items: 90,
  collections: 12,
  tags: 47,
};
